# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-14 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_postmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='postmeta',
            name='author',
        ),
        migrations.DeleteModel(
            name='postmeta',
        ),
    ]
