# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-14 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170914_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slider',
        ),
    ]
