# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-28 11:12
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170927_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opt',
            name='value',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
