# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
