# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20171007_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='opt',
            name='url',
            field=models.URLField(default='url = models.URLField(max_length = 255)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Category'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='url',
            field=models.URLField(blank=True, help_text='(\u067e\u06cc\u0634 \u0641\u0631\u0636 \u0627\u0633\u0644\u0634 \u0639\u0646\u0648\u0627\u0646 \u0645\u0637\u0644\u0628)'),
        ),
    ]
